# Generated by Django 2.2.2 on 2019-06-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '임패션 게시글', 'verbose_name_plural': '임패션 게시글'},
        ),
    ]
