# Generated by Django 2.2.2 on 2019-06-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impassionuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impassionuser',
            options={'verbose_name': '동아리원', 'verbose_name_plural': '동아리원'},
        ),
    ]
