# Generated by Django 2.2.2 on 2019-06-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impassionuser', '0003_impassionuser_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='impassionuser',
            name='cardinal_number',
            field=models.IntegerField(default=0, verbose_name='기수'),
            preserve_default=False,
        ),
    ]
